apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
  labels:
    app: dummy
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
