apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabadiaf
  labels:
    app: rabadiaf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabadiaf
  template:
    metadata:
      labels:
        app: rabadiaf
    spec:
      containers:
        - name: rabadiaf
          image: rabadiaf/ci-demo:latest
          ports:
            - containerPort: 80

