- name: Manage dummy pod on Kubernetes
  hosts: localhost
  connection: local
  environment:
    KUBECONFIG: "{{ lookup('env', 'KUBECONFIG') }}"
  tasks:
    - name: Delete existing dummy-pod if exists.
      shell: ./home/rabadiaf/actions-runner/run.sh
      shell: |
          kubectl delete pod -l app=dummy --ignore-not-found
      ignore_errors: true
