name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: run script runner
      run: ./home/rabadiaf/actions-runner/run.sh
    - name: Run Ansible playbook to apply pod
      run: ansible-playbook k8s/deployment.yaml  
    - name: Deploy to Minikube
      run: |
        kubectl get pods -n  github-actions
